### ISSUE TITLE
HMCatalog connection fails

### ISSUE THREAD

**Issue by NSchnitzler** [htreu/OpenHAB-HomeKit-Bridge#10]
The Connection to the Bridge worked time, so i was able to enter the code, but nothing more. Any other try to connect runs infinite. 

On the server side, the terminal looks like:
TCP server accepting connection on port: 52826
HAP Server is listening
open ws connection for switch characteristic.
open ws connection for switch characteristic.
open ws connection for switch characteristic.
open ws connection for switch characteristic.
open ws connection for switch characteristic.
open ws connection for switch characteristic.
open ws connection for switch characteristic.
open ws connection for switch characteristic.
open ws connection for switch characteristic.

that's all. At the time i had a short it connection, it was:
New Session 50165
Server Connection Established 60373
Identify!
Start Pair M1
Start Pair M3
Start Pair M5
Client Disconnected
Server Disconnected
New Session 50166
Server Connection Established 60387
Start Verify M1
Verify M1 Finished
Start Verify M3
M3: Verify Success
Characteristics.js:updateValue():NotEventEnabled
Characteristic.js:updateCharacteristicValue() without onUpdate function: true
Characteristics.js:updateValue():NotEventEnabled
Characteristic.js:updateCharacteristicValue() without onUpdate function: true
Client Disconnected
Server Disconnected
New Session 50167
Server Connection Established 60392
Start Verify M1
Verify M1 Finished
Start Verify M3
M3: Verify Success
Client Disconnected
Server Disconnected
New Session 50180
Server Connection Established 60411
Start Verify M1
Verify M1 Finished
Start Verify M3
M3: Verify Success
Client Disconnected
Server Disconnected

**Comment by htreu** [comment]
> Server Connection Established 60387
> Start Verify M1
> Verify M1 Finished
> Start Verify M3
> M3: Verify Success

this looks quite good. the encrypted connection is established.

> Characteristics.js:updateValue():NotEventEnabled
> Characteristic.js:updateCharacteristicValue() without onUpdate function: true

I haven't seen this one yet. Please post your configuration:

- sitemap
- iOS device + iOS version
- HomeKit App used for accessing the bridge

**Comment by NSchnitzler** [comment]
Yes, but this happens only one time and after writing the pin, i wasn't able to find accessories.
The HomeKit App was the HMCatalog example provided by apple used on a Iphone 5s with IOS 9.
The reduced sitemap for home kit is:
sitemap homekit
{
                Switch item=Light_WZ_Decke
                Switch item=Light_WZ_Wand
                Switch item=Light_WZ_ind
                Switch item=Light_Vitrinen
                Switch item=Light_Cook_Ceil
                Switch item=Light_Terasse
                Switch item=LEDs_Terasse
                Switch item=Teich_STD
                Switch item=Light_EZ_Theke                                                                   $
}

**Comment by htreu** [comment]
thanks for the report.
I haven't tested with iOS 9 yet. Please try to update the repository, ```rm -rf node_modules```, and ```npm install``` again. The underlying HAP-NodeJS lib was updated a few days ago to support iOS 9.

**Comment by NSchnitzler** [comment]
Done, but the same behavior. The app can't discover anything and the server doesn't go on after the open ws connection ....... lines

**Comment by NSchnitzler** [comment]
After deleting the persist folder and upgrade to IOS 9 Beta 2, i was able to connect and use siri.

thanks for your great work!

**Comment by htreu** [comment]
Excellent, I´m glad you solved it.
