### ISSUE TITLE
Suggestion to merge with https://github.com/nfarina/homebridge

### ISSUE THREAD

**Issue by DPD-30** [htreu/OpenHAB-HomeKit-Bridge#12]
The https://github.com/nfarina/homebridge has a plugin support for platforms.   If you adjusted this code to work in that then people would be able to use this and other integration platforms together without having to run multiple node apps.  I have an ISY controller and working on using openHAB for my non instieon devices.

**Comment by htreu** [comment]
The homebridge project is a great idea but in my opinion it integrates the different technologies on the wrong level (read: different level then OpenHAB). the OpenHAB-HomeKit-Bridge tries to be an easy to use add-on for OpenHAB to support HomeKit but integration is all done in OpenHAB itself.
As I restructure the OpenHAB-HomeKit-Bridge to support the new API style of HAP-NodeJS I might try to bring it closer to the plugin style of homebridge.

**Comment by andreheuer** [comment]
I am looking forward for the restructured version as I have problems in pairing my iOS device to the OpenHAB bridge (after verfify m3 success, the devices are still not paired :-(). However, HAP-NodeJS with its sample items works well for me.

**Comment by htreu** [comment]
Thanks for mentioning the problems. Please update your sources, delete _node_modules_ & _persist_ folder and
```js
npm install
```
again. It will now pull an early version of HAP-NodeJS which allows iOS8 for correct pairing. Make sure not to expose a roller shutter in your sitemap. This is not supported at the moment.

**Comment by andreheuer** [comment]
Thank you for the update. I immediately tested the new version.

However, I still have the same problem as described in #13 :-(

**Comment by htreu** [comment]
Please delete _persist_ once again and also remove the existing pairing from iOS. Restart the bridge and pair again.

**Comment by andreheuer** [comment]
Sorry, that did not work. I still get the same error...

**Comment by htreu** [comment]
Please test again with the branch [new-api](https://github.com/htreu/OpenHAB-HomeKit-Bridge/tree/new-api) which builds upon the latest version of HAP-NodeJS.
Remember to
1. delete _node_modules_ folder
2. delete _persist_ folder
3. ```npm install```
4. remove bridge pairing from iOS
5. start the bridge and pair again

**Comment by andreheuer** [comment]
Ok, I have switched to the new-api branch and followed your steps.
The pairing works perfect now! Thank you!
However, after adding the OpenHab Bridge as accessory, there is only one available service: OpenHab Homekit bridge. And I cannot switch any device in the Openhab sitemap using homekit.

**Comment by htreu** [comment]
Please make sure to have a separate sitemap for the bridge which only consists of plain items w/o any frames.
Here is an example:
```
sitemap demo label="HomeKit" {
    Switch item=DemoSwitch label="Toggle Switch"
    Slider item=DimmedLight label="Dimmed Light" switchSupport
    Colorpicker item=RGBLight icon="slider"
}
```

**Comment by andreheuer** [comment]
Ok, that was the problem! Thank you! Now its working fine!!

**Comment by htreu** [comment]
To come back to the original question: I have no plans to merge with homebridge, here is why:
1. OpenHAB-HomeKit-Bridge should only be one of many control points for smart home accessories. The voice control gained by Siri is not what makes gadgets of different vendors 'smart'.
2. In my opinion openHAB does a really good job of integration of different accessories from different vendors and protocols. The effort in developing bindings should not be doubled just to adopt to HomeKit.
3. The exclusive bridging to openHAB allows for a focused development against one single service. This allows for a very slick implementation with very few dependencies.

**Comment by tolgraven** [comment]
Good reasoning imo! However I'm unable to get homebridge and openhab-homekit-bridge to run at the same time. Even when setting them up to run on different ports there still seems like something in the hap-nodejs backend tries to bind to the same port resulting in whatever opened last crashing. Do you know how to sort that?

**Comment by htreu** [comment]
I don't know how to circumvent the fixed ports. There is an issue at hap-nodejs for this: https://github.com/KhaosT/HAP-NodeJS/issues/131
