### ISSUE TITLE
Hangs on adding Accessory

### ISSUE THREAD

**Issue by grouchal** [htreu/OpenHAB-HomeKit-Bridge#13]
My iPhone can see the Bridge and I get prompted for the passcode - after that the iPhone hangs on Adding Accessory.

In the Bridge Log I can see

> TCP server accepting connection on port: 52826
> HAP Server is listening
> New Session 61378
> Server Connection Established 55288
> Start Pair M1
> Start Pair M3
> Start Pair M5
> Client Disconnected
> Server Disconnected
> New Session 61379
> Server Connection Established 55289
> Start Verify M1
> Verify M1 Finished
> Start Verify M3
> M3: Verify Success

It stops at this point

**Comment by htreu** [comment]
pls have a look at #12. You have to update sources, delete _node_modules_ & _persist_, reinstall and also remove the paired bridge in iOS. Then Pair again.
