### ISSUE TITLE
Can't find/connect accessory HMCatalog

### ISSUE THREAD

**Issue by degsmfan** [htreu/OpenHAB-HomeKit-Bridge#14]
iOS 9 - iPhone 6 Plus - Apple homekit sample code, unmodified HMCatalog

Seems to start fine....(see below) though for some reason when I go to search for accessories I can either not find anything or it does and when i try to add it it will say "error: object not found"

Im not sure if my config is correct as I couldn't seem to find a sample/default config in any docs.

# npm start -- --server 192.168.1.107:8480 --sitemap homekit

> OpenHAB-HomeKit-Bridge@1.0.0 start /root/github/OpenHAB-HomeKit-Bridge
> node index.js "--server" "192.168.1.107:8480" "--sitemap" "homekit"

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
OpenHAB Bridge starting...
processing widget: SwitchItem Living Room Light
processing widget: SwitchItem Dining Room Light
processing widget: SwitchItem Lamp
open ws connection for switch characteristic.
open ws connection for switch characteristic.
open ws connection for switch characteristic.

homekit.sitemap

sitemap homekit
{
Switch item=SW_LIVINGROOM 	labelcolor=["black"]
Switch item=SW_DININGROOM 	labelcolor=["black"] 
Switch item=LAMP			labelcolor=["black"] 
}

homekit.items

Switch LAMP				"Lamp"				{http=">[ON:GET:http://192.168.1.50/?ajaxc=1B21] >[OFF:GET:http://192.168.1.50/?ajaxc=1B20]"} 
Switch SW_LIVINGROOM 	"Living Room Light"	{http=">[ON:GET:http://192.168.1.50/?ajaxc=4LW21] >[OFF:GET:http://192.168.1.50/?ajaxc=4LW20]"} 

Switch SW_DININGROOM 	"Dining Room Light" {http=">[ON:GET:http://192.168.1.50/?ajaxc=4LW11] >[OFF:GET:http://192.168.1.50/?ajaxc=4LW10]"}

**Comment by degsmfan** [comment]
if it helps any i cloned KhaosT/HAP-NodeJS and don't have any problems detecting it, adding and controlling my items.... just not through openHAB :(

**Comment by htreu** [comment]
Please checkout the latest version and follow the steps 1 - 5 from [#12](https://github.com/htreu/OpenHAB-HomeKit-Bridge/issues/12#issuecomment-139606676).
I just started to update the version number to track log output. Your sitemap and the initial log output looks good though.

**Comment by degsmfan** [comment]
I have followed the steps though, still i get "No discovered Accessories" and i can not pair.
