### ISSUE TITLE
Question: Prevent multiple commands

### ISSUE THREAD

**Issue by tex4ever** [htreu/OpenHAB-HomeKit-Bridge#17]
Hi, thanks for this great project! It works awesome!

But I have a question/problem:
I named all my lamps like this:

Lamp Couch
Lamp Table
Lamp Kitchen
Lamp Toilette

When I now say: Siri, switch Lamp Table on, then Siri sometiems doesn't understand Table and will command "Switch Lamp on". All lamps in the house will switch on then. -> My wife killed me already, because I tried this out in the night and she and my kids were sleeping and all lights went on. ;-)

Can you tell me how I can solve this?

Thanks a lot! ;-)
Philipp

**Comment by htreu** [comment]
My lights are just named after the place they are installed: "Livingroom, Kitchen, ..." HomeKit _knows_ this devices are lights so the command "switch on the kitchen lights" will target the right device.
