### ISSUE TITLE
Question: German command for roller shutter?

### ISSUE THREAD

**Issue by tex4ever** [htreu/OpenHAB-HomeKit-Bridge#18]
What is the Siri command in german to control shutters?

"Fahre Rolladen XY hoch" geht nicht

I did try a lot, the only thing what Siri seems to recognize is:

"Setze Rolladen XY auf 100%"

Then Siri awnsers: "Es gibt keine Jalousien".

Item in "Haus.sitemap"
	Switch item=EG_Kueche_Rolladen_Links label="Rolladen Küche"

**Comment by htreu** [comment]
I am eager to learn that, too. I didn't succeed as yet. It would be the first thing in READE.MD if we find out :-)

**Comment by tex4ever** [comment]
ok, I let you know when I find it out first. ;-)

**Comment by tex4ever** [comment]
Hi, I think I found the German command for the shutters. My item in my sitemap is:

	//Rollershutter/Blinds
	Switch item=EG_Wohnzimmer_Rolladen_Links label="Wohnzimmer links" mappings=[0="ZU", 100="AUF"]

When I say: 
Mach den Rolladen Wohnzimmer links auf -> then Siri awnsers 0.
Mach den Rolladen Wohnzimmer links zu -> then Siri awnsers 100.

Those values seems to be defined from you in the Rollershutteritem.js -> but the command isn't executed for any reasons, shutters don't go up oder down. Maybe there is an issue in the script?!?

**Comment by JanGoe** [comment]
Hello,

i have the same problem, but i have write a rule that send the command up/down if the item revice command 0 or 100

Exempel:
// test rule
rule "test sirs zu"
when
Item Schlafzimmer_Rolladen received command 0
then
sendCommand(Schlafzimmer_Rolladen,STOP)
sendCommand(Schlafzimmer_Rolladen,DOWN)
end
rule "test sirs auf"
when
Item Schlafzimmer_Rolladen received command 100
then
sendCommand(Schlafzimmer_Rolladen,STOP)
sendCommand(Schlafzimmer_Rolladen,UP)
end

**Comment by htreu** [comment]
Running iOS 9.2.1 and the latest OpenHAB-Homekit-Bridge (35eafded8571a373c5a04c38afcb000cd26e3e47) the german commands like "Schließe den Rollladen im Wohnzimmer" or "Öffne den Rolladen Wohnzimmer links" works like a charm now :-)

@JanGoe I now also have this workaround as my rollershutters only understand up/down commands. Thanks for this solution.

**Comment by TRIROG** [comment]
And what works in english?

**Comment by Xento** [comment]
I have still an issue.
When I say "Schließe den Rollladen Terrasse" it works, but when I say "Öffne den Rollladen Terasse" Siri says "Das kann ich leider nicht".

**Comment by htreu** [comment]
I just figured out that saying "Jalousie" instead of "Rollladen" works most of the time. The `open` command "öffne Jalousie" or "öffne Rollladen" never works _except_ of "öffne alle Rollladen!" which will open all the shutters in the house. Opening single shutters always requires me to say "Setze Jalousie Esszimmer auf 100%".
