### ISSUE TITLE
Bridge will not publish accessories

### ISSUE THREAD

**Issue by htreu** [htreu/OpenHAB-HomeKit-Bridge#25]
Like stated in #19 the bridge is broken at the moment. It will start w/o issues but does not show up in the iOS HomeKit apps.

**Comment by velaar** [comment]
Is there a chance that Apple somehow blocked it? "MyTouchHome" is saying "Accessory if blocked".

**Comment by dz1989** [comment]
Hi, my Bridge freezes at "open ws connection for url......"
No connected to Bridge possible with Eve app on iPhone.

Is that a issue of this problem? Or is there something different wrong?

**Comment by htreu** [comment]
> Is that a issue of this problem?
yes, thats the last thing which is logged. after that the logging should show connection procedure to iOS. The bridge is not frozen, there is some strange connection problem.

**Comment by dz1989** [comment]
Ok, thank you. Hope you are able to fix that. *fingers crossed*
