### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by pinki** [htreu/OpenHAB-HomeKit-Bridge#3]
The program crashes on startup on my system (Raspberry Pi with Raspbian)

Log:
<pre><code>0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--server',
1 verbose cli   'localhost:8080' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart OpenHAB-HomeKit-Bridge@0.0.1
7 info start OpenHAB-HomeKit-Bridge@0.0.1
8 verbose unsafe-perm in lifecycle true
9 info OpenHAB-HomeKit-Bridge@0.0.1 Failed to exec start script
10 verbose stack Error: OpenHAB-HomeKit-Bridge@0.0.1 start: `node openHABBridge.js --server localhost:8080`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid OpenHAB-HomeKit-Bridge@0.0.1
12 verbose cwd /home/pinki/OpenHAB-HomeKit-Bridge
13 error Linux 3.18.7-v7+
14 error argv "/usr/bin/node" "/usr/bin/npm" "start" "--" "--server" "localhost:8080"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error OpenHAB-HomeKit-Bridge@0.0.1 start: `node openHABBridge.js --server localhost:8080`
18 error Exit status 1
19 error Failed at the OpenHAB-HomeKit-Bridge@0.0.1 start script 'node openHABBridge.js --server localhost:8080'.
19 error This is most likely a problem with the OpenHAB-HomeKit-Bridge package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node openHABBridge.js --server localhost:8080
19 error You can get their info via:
19 error     npm owner ls OpenHAB-HomeKit-Bridge
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
</code></pre>

**Comment by pinki** [comment]
On another Raspberry it works without problems...

**Comment by pinki** [comment]
On Raspberry Pi there is a startup error.
To fix it, lib/switchItem.js has to be renamed to lib/SwitchItem.js

**Comment by brutevinch** [comment]
i've got problem((((

OpenHAB Bridge starting...
/usr/src/OpenHAB-HomeKit-Bridge/lib/ItemProvider.js:4
  for (var i = 0; i < widgets.length; i++) {
                             ^
TypeError: Cannot read property 'length' of undefined
    at Object.parseSitemap (/usr/src/OpenHAB-HomeKit-Bridge/lib/ItemProvider.js:4:30)
    at /usr/src/OpenHAB-HomeKit-Bridge/openHABBridge.js:32:30
    at Request._callback (/usr/src/OpenHAB-HomeKit-Bridge/lib/RestClient.js:11:7)
    at Request.self.callback (/usr/src/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:354:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/src/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:1207:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/src/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:1153:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

npm ERR! Linux 3.18.7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--server" "10.0.1.250:8080"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! OpenHAB-HomeKit-Bridge@0.0.1 start: `node openHABBridge.js --server 10.0.1.250:8080`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the OpenHAB-HomeKit-Bridge@0.0.1 start script 'node openHABBridge.js --server 10.0.1.250:8080'.
npm ERR! This is most likely a problem with the OpenHAB-HomeKit-Bridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node openHABBridge.js --server 10.0.1.250:8080
npm ERR! You can get their info via:
npm ERR!     npm owner ls OpenHAB-HomeKit-Bridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/OpenHAB-HomeKit-Bridge/npm-debug.log

**Comment by htreu** [comment]
please post the homekit.sitemap for further support.
