### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by thiloackermann** [htreu/OpenHAB-HomeKit-Bridge#33]
I get the following error:

OpenHAB Bridge starting...
/Users/thiloackermann/Downloads/last/lib/SitemapParser.js:25
        if (!widget.item) {
                   ^
TypeError: Cannot read property 'item' of undefined

I'm using node 0.12.0 and openHAB 1.8.

**Comment by htreu** [comment]
please post your sitemap

**Comment by htreu** [comment]
and please update to the latest sources.

**Comment by thiloackermann** [comment]
sitemap:

sitemap demo label="HomeKit" {
  # On/Off Item (lights, outlets)
  Switch item=swHndhz label="Toggle Switch"
}
