### ISSUE TITLE
Colorpicker item does not work

### ISSUE THREAD

**Issue by nbittmann** [htreu/OpenHAB-HomeKit-Bridge#35]
Hi Guys,

I was just wondering I can't seem to get the colorpicker item to work is this not supported or how would I make it appear?

Sitemap contains:

```
   Colorpicker item=Livingroomargb icon="colorwheel" label="Color door"
```

Tried without the label as well no change though

Openhab v. 1.7.1
home bridge latest version here from github

Thanks

**Comment by nbittmann** [comment]
Just checked my Logs and the error I get is:

```
Platform - The widget 'Color door' of type ColorItem is an item not handled.
```

Hope someone can help ?

**Comment by htreu** [comment]
Please provide a more broad description: which log file? And please provide the json sitemap from http://<openhab-host>/rest/sitemaps/<sitemap-name>?type=json
