### ISSUE TITLE
Doesn't work with openhab2

### ISSUE THREAD

**Issue by brutevinch** [htreu/OpenHAB-HomeKit-Bridge#4]
Doesn't work with openhab2. Please port to openhab2 because first openhab is no more perspective. Development is focused on openhab2.

root@Home /usr/src/OpenHAB-HomeKit-Bridge # npm start --server=10.0.1.250:8080

> OpenHAB-HomeKit-Bridge@0.0.1 start /usr/src/OpenHAB-HomeKit-Bridge
> node openHABBridge.js

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
OpenHAB Bridge starting...
/usr/src/OpenHAB-HomeKit-Bridge/lib/ItemProvider.js:4
  for (var i = 0; i < widgets.length; i++) {
                             ^
TypeError: Cannot read property 'length' of undefined
    at Object.parseSitemap (/usr/src/OpenHAB-HomeKit-Bridge/lib/ItemProvider.js:4:30)
    at /usr/src/OpenHAB-HomeKit-Bridge/openHABBridge.js:32:30
    at Request._callback (/usr/src/OpenHAB-HomeKit-Bridge/lib/RestClient.js:11:7)
    at Request.self.callback (/usr/src/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:354:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/src/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:1207:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/src/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:1153:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

npm ERR! Linux 3.18.7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--server=10.0.1.250:8080"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! OpenHAB-HomeKit-Bridge@0.0.1 start: `node openHABBridge.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the OpenHAB-HomeKit-Bridge@0.0.1 start script 'node openHABBridge.js'.
npm ERR! This is most likely a problem with the OpenHAB-HomeKit-Bridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node openHABBridge.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls OpenHAB-HomeKit-Bridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/OpenHAB-HomeKit-Bridge/npm-debug.log

**Comment by htreu** [comment]
Since OpenHAB 2 is in an early pre alpha state and the current OpenHAB code is under further development I will not add OpenHAB 2 support in the near future. The main focus is to extend the item types supported and stability.
