### ISSUE TITLE
Contact and String Items not Showing up

### ISSUE THREAD

**Issue by JoeCob** [htreu/OpenHAB-HomeKit-Bridge#41]
Hi. When I start the HomeBridge I can see my Contact and String itens are detected as accessories: 

Starting the bridge OpenHAB-Bridge ...
  AccessoryProvider processing widget: NumberItem Temperature [31.0 °C] +0ms
  AccessoryProvider processing widget: NumberItem Humidity  [48.0 %] +12ms
  AccessoryProvider processing widget: ContactItem Portao da Garagem [CLOSED] +5ms
  AccessoryProvider processing widget: ContactItem Portao da Rua  [CLOSED] +0ms
  AccessoryProvider processing widget: ContactItem GarageMotion [CLOSED] +0ms
  AccessoryProvider processing widget: SwitchItem Open Gate +0ms
  AccessoryProvider processing widget: StringItem Carro Estacionado [SIM] +3ms
  AccessoryProvider processing widget: SwitchItem Garage Light +0ms
  Accessory [OpenHAB-Bridge] Creating new AccessoryInfo for our HAP server +7ms
  Accessory [OpenHAB-Bridge] Creating new IdentifierCache +1ms
  EventedHTTPServer Server listening on port 52826 +17ms
  UpdateListener open ws connection for url http://10.0.1.200:8080/rest/items/Temperature_Garage +19ms
  UpdateListener open ws connection for url http://10.0.1.200:8080/rest/items/Humidity_Garage +3ms
  UpdateListener open ws connection for url http://10.0.1.200:8080/rest/items/Light_Outdoor_Garage +1ms
  UpdateListener open ws connection for url http://10.0.1.200:8080/rest/items/Button_OpenGate +1ms
  TemperatureSensor temperature received message: 47.0 +34s

But listeners are not added to them, just for the Switch and NumberItens. 

At the home kit apps (elgato and idevices) I cant see the Contact and String itens, just the ones with the listeners (Switch and NumberItem). 

Just wondering if thats correct or they should have some specific setting to work.

**Comment by htreu** [comment]
This is actually a bug. Please check out the latest version since we had a major refactoring. ContactItems should work now including update listeners.
