### ISSUE TITLE
Items from sitemap not fetched correctly

### ISSUE THREAD

**Issue by FredericMa** [htreu/OpenHAB-HomeKit-Bridge#43]
Hi all,

I installed the OpenHAB-HomeKit-Bridge and it seems to start fine and i don't get any errors,
However the when I start the bridge the only printout i get is:
Starting the bridge myOpenHAB-Bridge ...

I start it with the following parameters:
npm start -- --name "myOpenHAB-Bridge" --server 127.0.0.1:8080 --sitemap homekit

The NPM version is 2.14.9 and the NodeJS version is v0.12.12.

When i take a look in the requests log of OpenHAB itself I get the following:
127.0.0.1 -  -  [15/Mar/2016:12:43:32 +0000] "GET /rest/sitemaps/homekit?type=json HTTP/1.1" 200 1353 
127.0.0.1 -  -  [15/Mar/2016:12:43:33 +0000] "GET /rest/items/DimmedLight/state?type=json HTTP/1.1" 101 0 
127.0.0.1 -  -  [15/Mar/2016:12:43:33 +0000] "GET /rest/items/DemoSwitch/state?type=json HTTP/1.1" 101 0 
127.0.0.1 -  -  [15/Mar/2016:12:43:33 +0000] "GET /rest/items/Shutter_GF_Living/state?type=json HTTP/1.1" 101 0 
127.0.0.1 -  -  [15/Mar/2016:12:43:33 +0000] "GET /rest/items/RGBLight/state?type=json HTTP/1.1" 101 0 
127.0.0.1 -  -  [15/Mar/2016:12:43:33 +0000] "GET /rest/items/Temperature_GF_Living/state?type=json HTTP/1.1" 101 0 

So it looks like the sitemap is fetched correctly but the fetching of the individual items seems to fail.
The last number of every log entry stands for the number of bytes returned.
When i make the same request for for example the DemoSwitch via a browser i get a valid response:
127.0.0.1 -  -  [15/Mar/2016:12:52:13 +0000] "GET /rest/items/DemoSwitch/state?type=json HTTP/1.1" 200 3 

Does somebody has any idea what is wrong, or what I am doing wrong?

Thanks a lot!

Greetings,
Frederic

**Comment by mystgd** [comment]
I have the same Problem, Version NPM 2.14.4 and NodeJS v4.1.2 Greetings, Stefan

**Comment by FredericMa** [comment]
I tried this one and this is working fine for me:
https://github.com/nfarina/homebridge

**Comment by htreu** [comment]
Try to start with `DEBUG=*,-babel npm start -- ...` to enable debug messages. The 0 byte and 101 code come from the WebSocket listeners to the single items. The listeners will receive updates form openHAB and propagate them to iOS.

**Comment by mystgd** [comment]
thank you htreu it works,
but now i have the same problem as described here:
https://github.com/htreu/OpenHAB-HomeKit-Bridge/issues/44
the sitemap loaded but MyTouchHome or EVE just show 1 accessory.

**Comment by htreu** [comment]
Should be fixed with #47.
