### ISSUE TITLE
OpenHAB-Bridge shows up as accessory instead of actual devices

### ISSUE THREAD

**Issue by timvanmeurs** [htreu/OpenHAB-HomeKit-Bridge#44]
I've installed the plugin and it starts normally. After opening EVE and adding the accessory, EVE shows just 1 accessory; the plugin and not the 3 switches i have configured in the separate sitemap.
Any clue as to why this is happening or how to resolve it ?

**Comment by manroh** [comment]
I've faced with the same problem. Bridge is discorverd under Accessories but device list remains empty. My setup worked in the past and I neither changed the bridge nor did I change openhab. Maybe an issue with iOS 9.3? Upgraded just a few days ago. I also removed the database under the persist folder an registered the bridge under a different name without any positive effect.

**Comment by timvanmeurs** [comment]
i tried this with an iPhone with iOS9.1 and got the same result. Doesn't seem to be an iOS issue.

**Comment by htreu** [comment]
Please check again. Should be fixed with 53bb001df1bd6cbf9af71f02c07770518db21952  see #47.
