### ISSUE TITLE
Elgato Eve - Extreme Brightening Lag & On to 1%

### ISSUE THREAD

**Issue by BucketofCookies** [htreu/OpenHAB-HomeKit-Bridge#45]
I installed OpenHAB with the InsteonPLM binding and have a number of Insteon dimmer items.  Everything is very responsive through the OpenHAB web interface and through the OpenHAB iOS app.  I installed OpenHAB-HomeKit-Bridge without any issues.  I attached the bridge to Elgato Eve on iOS.  All of the items pulled in and are controllable through the app.  There are no issues with Siri interactions like "Turn ON/OFF" or "Set to 50%".

The issue:
Dimmer items in Eve are exhibiting two issues.

1) Tapping ON sets them to 1%
2) The brightness slider has extreme lag.  If I swipe the slider quickly from 0% to 100%, the slider and its corresponding light will brighten at random increments from 0% to 100% over the course of a minute; as if the slider is sending tens or hundreds of requests to "set to 1%, set to 2%, set to 5%" etc.

Is anyone else experiencing these two issues?

**Comment by BrianTillman** [comment]
Same behavior here for devices bound with the InsteonPLM binding, though I'm using the "Home" app on iOS 10, build 14A5297c instead of Elgato Eve.

**Comment by BrianTillman** [comment]
Removing "switchSupport" from the item in the sitemap improves the experience for me. Tapping ON will set the dimmer to 100%, though the readout on the "Home" app shows it bouncing back to 1% before retuning and remaining at 100%.

**Comment by htreu** [comment]
Thanks @BrianTillman for the input. If this is still an issue please reopen.
