### ISSUE TITLE
Instruction for homebridge install Windows

### ISSUE THREAD

**Issue by apache-123** [htreu/OpenHAB-HomeKit-Bridge#46]
Hi,

I Have Opehhab 1.8.2 installed on a windows PC that is on all the time at home. I have An Aeotec Gen5 stick and all is working well. I now want to progress to the Home Bridge  integration. All instructions seem to point to Linux/Mac/Raspberry Pi but nothing for windows. Could you please help me get lazier :D 
Cheers

**Comment by htreu** [comment]
Hi, I don't think this one is for the lazy right now ;-) You basically need a running nodeJs distribution and the avahi/mdns/bonjour compatibility layer for windows. Read here how to install it: https://github.com/agnat/node_mdns

After that make sure to run `npm install` in the home directory of the OpenHAB-Homekit-Bridge. Good luck.
