### ISSUE TITLE
text instead of slider for volume control

### ISSUE THREAD

**Issue by mbelleville** [htreu/OpenHAB-HomeKit-Bridge#51]
I am trying to set up a control for "kitchen volume" that I can adjust by saying "hey siri, set the kitchen volume to 50".  I like this much more than saying "dim the kitchen volume to 50"

Slider item=KitchenSiriVolumeDimmer label="kitchen volume" 
- works just fine, but I have to use the word "dim" to adjust the level

Text item=KitchenVolumeSiriNumber label="kitchen volume" 
Text item=KitchenVolumeSiriNumber label="kitchen volume [:%d]" 
-neither of these work

am I doing it wrong?

**Comment by htreu** [comment]
You are not doing it wrong. Text items are not picked up as dimmers/sliders right now. Only Contact, Temperature or read only labels.
In addition I´m not aware of a HomeKit type to control `volume`.
