### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by curryking1607** [htreu/OpenHAB-HomeKit-Bridge#52]
Hello,
I am using Homekit <> openHab <> KNX as many of you probably, the Debian it all runs down is in a VM on my PC with its own IP and so on...
Installed the Demo content on openHab(renamed the sitemap to homekit.sitemap),
configured KNX and Homekit, 
copied the [package.json here](https://github.com/htreu/OpenHAB-HomeKit-Bridge/blob/master/package.json) to my home folder (username ist lx).
When I start the openHab server in a Terminal and try to start the Homekit Bridge with

>  npm start -- --name "myOpenHAB-Bridge" --server localhost:8080 --sitemap homekit

I receive loads of errors:

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--name',
1 verbose cli   'myOpenHAB-Bridge',
1 verbose cli   '--server',
1 verbose cli   'localhost:8080',
1 verbose cli   '--sitemap',
1 verbose cli   'homekit' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart openHAB-HomeKit-Bridge@1.3.3
6 info start openHAB-HomeKit-Bridge@1.3.3
7 verbose unsafe-perm in lifecycle true
8 info openHAB-HomeKit-Bridge@1.3.3 Failed to exec start script
9 verbose stack Error: openHAB-HomeKit-Bridge@1.3.3 start: `node index.js start "--name" "myOpenHAB-Bridge" "--server" "localhost:8080" "--sitemap" "homekit"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid openHAB-HomeKit-Bridge@1.3.3
11 verbose cwd /home/lx
12 error Linux 3.16.0-4-amd64
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "--" "--name" "myOpenHAB-Bridge" "--server" "localhost:8080" "--sitemap" "homekit"
14 error node v4.4.5
15 error npm  v2.15.5
16 error code ELIFECYCLE
17 error openHAB-HomeKit-Bridge@1.3.3 start: `node index.js start "--name" "myOpenHAB-Bridge" "--server" "localhost:8080" "--sitemap" "homekit"`
17 error Exit status 1
18 error Failed at the openHAB-HomeKit-Bridge@1.3.3 start script 'node index.js start "--name" "myOpenHAB-Bridge" "--server" "localhost:8080" "--sitemap" "homekit"'.
18 error This is most likely a problem with the openHAB-HomeKit-Bridge package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index.js start "--name" "myOpenHAB-Bridge" "--server" "localhost:8080" "--sitemap" "homekit"
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs openHAB-HomeKit-Bridge
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls openHAB-HomeKit-Bridge
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

hope you can help me, and please be patient with me since debian is not my main OS,

curry

**Comment by htreu** [comment]
Did you do `npm install` or `npm update` from a previous install? Is there any other output after you commit the npm start command?
Copying the package.json is not sufficient. You have to clone the complete repo and do `npm install` in the root directory of the project.

**Comment by curryking1607** [comment]
Ok, what I did now is: Download the repo, extract it. 
cd / to the repo
run npm install 
and I'm starting with:

 npm start -- --name "PH Bridge" --server 192.168.122.124:8080 --sitemap homekit


This gets me the following error:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--name',
1 verbose cli   'PH Bridge',
1 verbose cli   '--server',
1 verbose cli   '192.168.122.124:8080',
1 verbose cli   '--sitemap',
1 verbose cli   'homekit' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart openHAB-HomeKit-Bridge@1.3.3
6 info start openHAB-HomeKit-Bridge@1.3.3
7 verbose unsafe-perm in lifecycle true
8 info openHAB-HomeKit-Bridge@1.3.3 Failed to exec start script
9 verbose stack Error: openHAB-HomeKit-Bridge@1.3.3 start: `node index.js start "--name" "PH Bridge" "--server" "192.168.122.124:8080" "--sitemap" "homekit"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid openHAB-HomeKit-Bridge@1.3.3
11 verbose cwd /home/lx/OpenHAB-HomeKit-Bridge-master
12 error Linux 3.16.0-4-amd64
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "--" "--name" "PH Bridge" "--server" "192.168.122.124:8080" "--sitemap" "homekit"
14 error node v4.4.5
15 error npm  v2.15.5
16 error code ELIFECYCLE
17 error openHAB-HomeKit-Bridge@1.3.3 start: `node index.js start "--name" "PH Bridge" "--server" "192.168.122.124:8080" "--sitemap" "homekit"`
17 error Exit status 1
18 error Failed at the openHAB-HomeKit-Bridge@1.3.3 start script 'node index.js start "--name" "PH Bridge" "--server" "192.168.122.124:8080" "--sitemap" "homekit"'.
18 error This is most likely a problem with the openHAB-HomeKit-Bridge package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index.js start "--name" "PH Bridge" "--server" "192.168.122.124:8080" "--sitemap" "homekit"
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs openHAB-HomeKit-Bridge
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls openHAB-HomeKit-Bridge
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by htreu** [comment]
Does `npm install` run w/o errors? Is there any other output in-between the start command and the npm information? Please paste the full contents of your terminal. You may even start with `DEBUG=*,-babel npm start -- --name "PH Bridge" --server 192.168.122.124:8080 --sitemap homekit` to see some more debug information.

**Comment by curryking1607** [comment]
sorry for the late reply,
npm install runs errorless in the terminal, npm-debug.log says:
> error install Couldn't read dependencies
verbose stack Error: Fialed to parse json
verbose stack No data, empty input at 1:1

this is what the debug log says by running the debug aswell.
My machine is quite straight-forward: 
User lx password: root
and root password is root, aswell.

everything I run is runned by root.

**Comment by htreu** [comment]
Just to be clear: You did `git clone https://github.com/htreu/.....` then `cd OpenHAB-HomeKit-Bridge` then `npm install`?
The message seems to indicate that npm does not see the package.json in the root of the project directory.
Pls have a look at this thread for some more ideas: http://stackoverflow.com/questions/18401934/couldnt-read-dependencies-error-with-npm

**Comment by curryking1607** [comment]
Yes, everything you said.
There seemed to be a problem with this though, and after I re-installed the package it gets me a different error (yay):

TypeError: Cannot read property 'homepage' of undefined
Exit Status 1

**Comment by htreu** [comment]
Please do a `curl -v http://192.168.122.124:8080/rest/sitemaps/homekit` and post the output.

**Comment by curryking1607** [comment]
`root@debian:/OpenHAB-HomeKit-Bridge# curl -v http://192.168.122.124:8080/rest/sitemaps/homekit
* Hostname was NOT found in DNS cache
*   Trying 192.168.122.124...
* Connected to 192.168.122.124 (192.168.122.124) port 8080 (#0)
> GET /rest/sitemaps/homekit HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 192.168.122.124:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 31 May 2016 23:09:07 GMT
< X-Atmosphere-first-request: true
< X-Atmosphere-tracking-id: e7f4bea2-7dd9-49fd-bfbf-2ac116d6d47b
< Expires: -1
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Content-Type: application/xml
< Content-Length: 319
* Server Jetty(8.1.3.v20120522) is not blacklisted
< Server: Jetty(8.1.3.v20120522)
< 
* Connection #0 to host 192.168.122.124 left intact
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><sitemap><name>homekit</name><label>HomeKit</label><link>http://192.168.122.124:8080/rest/sitemaps/homekit</link><homepage><id>demo</id><title>HomeKit</title><link>http://192.168.122.124:8080/rest/sitemaps/homekit/demo</link><leaf>false</leaf></homepage></sitemap>root@debian:/OpenHAB-HomeKit-Bridge# curl -v http:/root@debian:/OpenHAB-HomeKit-Bridge# 

`

**Comment by htreu** [comment]
It seems all the xml tags are missing. Please try again with `curl -v http://192.168.122.124:8080/rest/sitemaps/homekit?type=json`. We are getting there :-)

**Comment by curryking1607** [comment]
> root@debian:/OpenHAB-HomeKit-Bridge# curl -v http://192.168.122.124:8080/rest/sitemaps/homekit?type=json
* Hostname was NOT found in DNS cache
*   Trying 192.168.122.124...
* Connected to 192.168.122.124 (192.168.122.124) port 8080 (#0)
> GET /rest/sitemaps/homekit?type=json HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 192.168.122.124:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 31 May 2016 23:15:56 GMT
< X-Atmosphere-first-request: true
< X-Atmosphere-tracking-id: b736644f-9b1f-451d-aaa6-ad410d39e2ab
< Expires: -1
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Content-Type: application/json
< Transfer-Encoding: chunked
* Server Jetty(8.1.3.v20120522) is not blacklisted
< Server: Jetty(8.1.3.v20120522)
< 
* Connection #0 to host 192.168.122.124 left intact
{"name":"homekit","label":"HomeKit","link":"http://192.168.122.124:8080/rest/sitemaps/homekit","homepage":{"id":"demo","title":"HomeKit","link":"http://192.168.122.124:8080/rest/sitemaps/homekit/demo","leaf":"false"}}root@debian:/OpenHAB-HomeKit-Bridge# 


So this is the other output I get. Really big thanks for your support, I really appreciate this!

**Comment by curryking1607** [comment]
Im sorry to remid you of my problem, you may accidently skipped it?

**Comment by htreu** [comment]
Guten morgen :-) Entschuldige die späte Rückmeldung.

The output of the `curl` command indicates your `homekit.sitemap` is empty. I did a test with an empty sitemap and got the same result. If your sitemap happens not to be empty please post it here for further analysation.

**Comment by curryking1607** [comment]
Good Evening//Guten Abend!

As a result of your answer I tried to use the "demo" sitemap and it worked!
But after I expanded the .items and .sitemap file it wont boot up again.

First there was an unknown error and now i've got the error code 1 from NPM,
but since then the terminal crashes as soon as I run the NPM command

**Comment by curryking1607** [comment]
EDIT: (rather update)
As it turns out my VM running Debian just totally crashed and won't boot.
Sh**.
I dont think I'll survive a reinstall of the system.
Thats really really bad because I just converted my whole KXN setup in the OpenHAB config.
Any way I can restore these configuration files?
I tried to map the VMDK file to my host but there was a file format error.

**Comment by htreu** [comment]
This really depends on the error which occurs. There should be at least some kind of output from the VM. I will close this issue for now and wish you good luck for the recovery.

**Comment by curryking1607** [comment]
Okay well thanks for the great support!
As I have to make a new VM in any case I just wanted to ask which linux distribution you would recommend. (It should be small and very fast to install and stable to run), like windows server for linux ;)

**Comment by htreu** [comment]
I would recommend to use a ready-to-run image with ubuntu or debian. But this highly depends on your taste on linux distros. You can download preinstalled images here: https://virtualboxes.org/images/

**Comment by curryking1607** [comment]
I tried everything I can but its not working. Different errors every time...
I know you have a lot to work on, but is it possible for you to create a preinstalled VM with the HK bridge?

This would be unbelievable!

**Comment by htreu** [comment]
I´m sorry, but this is completely out of scope.

**Comment by curryking1607** [comment]
Okay I can understand that. I just hoped you already had something like this (like a developing VM),
but I'll give it another try.
So please tell me whether I missed something:

- Download and install the VM and boot it up obviously
- comment out the install CD in the sources.list
- run apt-update and apt-upgrade
- apt-get install sudo and -curl
- curl -sL ... setup_4 sudo -E bash -
- sudo apt-get install nodejs
- sudo apt-get install build-essential
(checkpont: node -v and npm -v have output)
- install libavahi and npm update
- sudo apt-get install git
-  git clone github...
- cd to OpenHab...
- npm install
NPM install does work, but gives out these:
`Warning: to-iso-string has been deprecated
Warning: jade has been renamd to pug
Warning: Please update to minimatch 3.0.2
Warning: lodash is no longer maintained
Warning: Please update to minimatch 3.0.2
Warning: optional dep failed
[...]
Error: Tried to download: ..bignum-v0.12.5...tar.gz
Error: Pre built binaries not found for bignum`

Okay. Then I start using:

npm start -- --name "PH28 Bridge" --server 192.168.122.115:8080 --sitemap demo

I get 6 warnings:
The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi
Please fix your application to use the native API of Avahi
For more informartion see ...
The program 'nodejs' called ... which is not supported in the .. layer of Avahi
Please fix your application to use the native API of Avahi
For more information see...

But anyway it says 'Starting the bridge PH28 Bridge...'
Sadly I'm not able to find the Bridge in the HomeKit app...

Why is this so difficult? :D 

Thanks for your great support!!!!!

**Comment by albertovm** [comment]
What you did please? Thanx!
