### ISSUE TITLE
no items from sitemap loaded

### ISSUE THREAD

**Issue by alphaZ** [htreu/OpenHAB-HomeKit-Bridge#53]
I setup OpenHAB which is working as expected in switching KNX-based lights.

When I start the bridge i get:

hab@openhab:~/OpenHAB-HomeKit-Bridge-master$ npm start -- --name testhab --server 127.0.0.1:8080 --sitemap demo
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
Starting the bridge testhab ...

and then nothing ... no item will show up.

I have an Ubuntu vmware based installation running on a mac
nodejs is version 4.4.5
(same behavior with 4.2.x)

the sitemap is:
rainer@openhab:~/OpenHAB-HomeKit-Bridge-master$  cat ../openHAB/configurations/sitemaps/demo.sitemap 
sitemap demo label="demo" {
  Switch item=Wohnen_Wandleuchten label="Wohnen Wandleuchten"
}

Any idea?

Thanks,
Rainer

**Comment by htreu** [comment]
Hi, the bridge is not supposed to have any output when running. If you want some debug information run the bridge with `DEBUG=*,-babel npm start -- --name testhab --server 127.0.0.1:8080 --sitemap demo`. When you start Elgato Eve, or any other HomeKit App on you iOS Device you should see the bridge and be able to pair.

**Comment by alphaZ** [comment]
Thanks you so much!!!
No items would show up in iOS, at some point I stopped adding and removing the device and only looked at the bridge output. My bad.
Suggestion: Add the debug hint to README.MD
