### ISSUE TITLE
Crash after a while

### ISSUE THREAD

**Issue by FluBBaOfWard** [htreu/OpenHAB-HomeKit-Bridge#54]
Assertion failed: (0), function uv_err_name, file ../deps/uv/src/uv-common.c, line 75.

Running on Mac OS X 10.11.5
openHAB 1.8.1
{ npm: '2.5.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.0',
  openssl: '1.0.1l',
  uv: '1.0.2',
  v8: '3.28.73',
  zlib: '1.2.8' }
node V0.12.0
Should I run it with debug somehow to get more info about it?

**Comment by htreu** [comment]
It seems your node version is outdated. Please try to update to node 0.12.7 or greater. Then run `npm update` or `rm -rf node_modules && npm install` to reinstall and compile the dependencies again.

**Comment by FluBBaOfWard** [comment]
Thanks!
I updated to latest node 4, couldn't update modules, had to remove/install.
Running fine for several days now =)
