### ISSUE TITLE
Outlets not working

### ISSUE THREAD

**Issue by TRIROG** [htreu/OpenHAB-HomeKit-Bridge#58]
I can't seem to be able to get the outlets to work.
This is the sitemap configuration i'm using.

```
Frame label="outlet" icon="outlet" { //# Outlets must be configured in a Frame.
    Switch item=LG_Power            label="TV"
    Switch item=Marantz_Power       label="Stereo"
    Switch item=HomeEasy_11             label="Dryer"
    Switch item=HomeEasy_04         label="Fan"
    Switch item=ELRO_D              label="Porch music" 
}
```

But they don't show up in homekit.

Here is the items file configuration for these switches

```
Switch LG_Power                 "LG"                    <television>
Switch Marantz_Power            "Marantz"               <receiver>
Switch HomeEasy_11          "Home Easy 11"          <"socket">
Switch HomeEasy_04          "Home Easy 04"          <"socket">
Switch ELRO_D               "Elro D"                <"socket">      
```

**Comment by htreu** [comment]
What does the sitemap look like in the browser? Do you see the frame with all the configured items?

**Comment by TRIROG** [comment]
Yes.
Could the use of tabulators be problematic?

**Comment by dfraser** [comment]
Try having a separate outlet frame for each outlet.  This works for me:
```
Frame label="outlet" icon="outlet" {
  Switch item=bathroomFan label="Bathroom Fan"
}

Frame label="outlet" icon="outlet" {
  Switch item=espresso label="Espresso Machine"
}
```

**Comment by TRIROG** [comment]
Nope ...
`	Frame label="outlet" icon="outlet" {
		Switch item=LG_Power label="1TV"
		}
	Frame label="outlet" icon="outlet" {
		Switch item=Marantz_Power label="1Stereo"
		}`
Still no joy ... they show up&work normally though if i use them without the outlet tags
`	Switch item=LG_Power label="1TV"
	Switch item=Marantz_Power label="1Stereo"`

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)

**Comment by TRIROG** [comment]
Well ... i'll be darned ... today I did a "git pull" followed by "npm update" and now everything works ...
Btw ... what is the best way to stop the OpenHAB-HomeKit-Bridge i.e to reload a sitemap, or does it happen automagically?

**Comment by htreu** [comment]
Glad it works for you now! Reloading actually does not happen automatically. You have to restart the bridge manually by killing the process and start again. Feel free to open another issue for this feature request :-)
