### ISSUE TITLE
RollerShutterItem "No Response"

### ISSUE THREAD

**Issue by curryking1607** [htreu/OpenHAB-HomeKit-Bridge#59]
Hey, its me again.

Im super happy with your script it works like a charm.
But I have a problem concerning my shutters.
I configured them like openHab told me to, so
first group address: Up/Down
second group address: Stop
third group address: percentage 

But I get the notification "No response" in HomeKit.

Whats wrong?

Thanks

curry

**Comment by htreu** [comment]
Do your shutters support open/close to a specific percentage? OpenHAB-HomeKit-Bridge will always send a value `[0-100]` to openHAB.
In my case the shutters only support `UP` or `DOWN` commands. I therefore created a simple rule for every shutter in openHAB to turn the percentage values into commands:

```
// Esszimmer
rule Rollershutter_Esszimmer_up
when
    Item Shutter_GF_Essen received command 0
then
    sendCommand(Shutter_GF_Essen, UP)
end

rule Rollershutter_Esszimmer_down
when
    Item Shutter_GF_Essen received command 100
then
    sendCommand(Shutter_GF_Essen, DOWN)
end
```

**Comment by curryking1607** [comment]
Okay, that works great! 
Thanks for the great support
