### ISSUE TITLE
Implement Rollershutter

### ISSUE THREAD

**Issue by htreu** [htreu/OpenHAB-HomeKit-Bridge#7]

**Comment by lilalinux** [comment]
The Rollershutter works fine with the dimmer code :-)

  updateOpenHabItem(value, callback) {
		console.log("received rollershutter value from iOS: " + value + ' ' + this.url);

		if (this.updatingFromOpenHAB) {
			callback();
			return;
		}
		var command = 0;
		if (typeof value === 'boolean') {
			command = value ? '100' : '0';
		} else {
			command = "" + value;
		}
		request.post(
				this.url,
				{
					body: command,
					headers: {'Content-Type': 'text/plain'}
				},
				function (error, response, body) {
						if (!error && response.statusCode == 200) {
								console.log(body)
						}
						callback();
				}
		);
	};

**Comment by htreu** [comment]
cool. pull requests are welcome :-)

what is still open: update the CurrentPosition and PositionState while the roller shutter is moving.

**Comment by lilalinux** [comment]
BTW: Do you know the german Siri command for operating the shutters?

**Comment by lilalinux** [comment]
I added a pull request

**Comment by tex4ever** [comment]
Hi, could you please tell me how you got your shutters working? 

I have:
(in items)
Rollershutter EG_Wohnzimmer_Rolladen_Links "Fenster links" (EG_Wohnzimmer_Rolladen) { knx="6/1/3,6/2/3" } 

(in sitemap)
Switch item=EG_Wohnzimmer_Rolladen_Links label="Wohnzimmer links"

Now, when I say in German:
- Setze Rolladen Wohnzimmer links auf 0%. -> nothing happens
- I tried several other stuff, but when I say: Setze Rolladen auf 0%. then Siri recognize my item, but doesn't do anything. Strange is to, that Siri says: Setze Rolladen Wohnzimmer auf %. (without a number, just %).

How did you get this working? Do you say: Dimme Wohnzimmer links auf 0%? Could you please explain how you accomplished this? ;-) 

Thanks a lot ;-)

**Comment by lilalinux** [comment]
@tex4ever You need to create a scene. There is currently no workable RollerShutter voice command in Siri (although Siri's "error message" indicates, that it does know "something" about RollerShutter.

**Comment by JanGoe** [comment]
Hello,

any news for the RollerShutter possible ?

**Comment by lilalinux** [comment]
Not that I'm aware of, but you can use a scene to workaround

**Comment by htreu** [comment]
Rollershutters do work as of 35eafded8571a373c5a04c38afcb000cd26e3e47 (basic implementation). See #18 for german voice commands and sample rules to control up/down shutters.
