### ISSUE TITLE
Install on debian fails

### ISSUE THREAD

**Issue by NSchnitzler** [htreu/OpenHAB-HomeKit-Bridge#9]
on my debian the install fails with the following comments:

npm install
 
> bignum@0.9.2 install /root/OpenHAB-HomeKit-Bridge/node_modules/HAP-NodeJS/node_modules/srp/node_modules/bignum
> node-gyp configure build

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-686-pae
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /root/OpenHAB-HomeKit-Bridge/node_modules/HAP-NodeJS/node_modules/srp/node_modules/bignum
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> curve25519@1.0.0 install /root/OpenHAB-HomeKit-Bridge/node_modules/HAP-NodeJS/node_modules/curve25519
> node-gyp rebuild

node.js:815
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Function.startup.resolveArgv0 (node.js:815:23)
    at startup (node.js:58:13)
    at node.js:906:3
npm ERR! bignum@0.9.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.9.2 install script.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-686-pae
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/OpenHAB-HomeKit-Bridge
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
> mdns@2.2.9 install /root/OpenHAB-HomeKit-Bridge/node_modules/HAP-NodeJS/node_modules/mdns
> node-gyp rebuild

**Comment by htreu** [comment]
It seems you are running node v0.10.29. Please try node v0.12.x.

**Comment by NSchnitzler** [comment]
after that, i got the error:
Error: Cannot find module './SwitchItem.js'
because the file was named 'switchItem.js'
after renaming i get:
OpenHAB Bridge starting...
/root/OpenHAB-HomeKit-Bridge/lib/ItemProvider.js:11
          link: widget.item.link,
                           ^
TypeError: Cannot read property 'link' of undefined
    at Object.parseSitemap (/root/OpenHAB-HomeKit-Bridge/lib/ItemProvider.js:11:28)
    at /root/OpenHAB-HomeKit-Bridge/openHABBridge.js:34:30
    at Request._callback (/root/OpenHAB-HomeKit-Bridge/lib/RestClient.js:11:7)
    at Request.self.callback (/root/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:354:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/root/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:1207:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/root/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:1153:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

**Comment by htreu** [comment]
Please make sure the homekit.sitemap does only consist of widgets and very widget needs to define an existing item. Frames or Groups are not supported.

**Comment by htreu** [comment]
I also did a quick fix, so "empty widgets" will not be parsed any more.
